spring.application.name=backend-spring
server.port=5010
management.endpoints.web.exposure.include=health,info
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:app}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
